name: "JAR to Executable"
description: "Runs a specified JAR and saves the resulting standalone executable to Output"
inputs:
  id:
    description: "ID of the program (minus extension)"
    required: true
  name:
    description: "Name of the program. Default to `id` if unspecified."
    required: false
  icon:
    description: "Path to the icon (.png on Linux/.ico on Windows)"
    required: false
  desktop-file:
    description: "Path to the desktop file (mandatory on Linux)"
    required: false
  input:
    description: "Path to the JAR file (Linux) or to jpackage generated app-image folder (Windows)"
    required: true
  output:
    description: "Path to save the output"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build AppImage (Linux)
      if: runner.os == 'Linux'
      shell: bash
      env:
        PROGRAM: "${{ inputs.id }}"
        PROGRAM_NAME: "${{ inputs.name }}"
        PROGRAM_ICON: "${{ inputs.icon }}"
        PROGRAM_DESKTOP_FILE: "${{ inputs.desktop-file }}"
        INPUT: "${{ inputs.input }}"
        OUTPUT: "${{ inputs.output }}"
      run: |
        chmod +x ${{ github.action_path }}/package.sh
        ${{ github.action_path }}/package.sh
        
    - name: Build Portable EXE (Win)
      if: runner.os == 'Windows'
      shell: pwsh
      env:
        PROGRAM: "${{ inputs.id }}"
        PROGRAM_NAME: "${{ inputs.name }}"
        ICON: "${{ inputs.icon }}"
        INPUT: "${{ inputs.input }}"
        OUTPUT: "${{ inputs.output }}"
      run: |
        $archive = "$env:PROGRAM.7z"
        $lzma_download_url = "https://github.com/ip7z/7zip/releases/latest/download/lzma2501.7z"
        $rcedit_download_url = "https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe"

        # Fetch 7-Zip SFX executable header
        Invoke-WebRequest -Uri $lzma_download_url -OutFile lzma.7z
        7z e lzma.7z 7zS2con.sfx -r -y
        Remove-Item lzma.7z -Force

        # Compress the folder into archive
        7z a $archive $env:INPUT

        # Combine SFX header + archive into final portable executable
        Get-Content 7zS2con.sfx, $archive -AsByteStream -ReadCount 0 | Set-Content $env:OUTPUT -AsByteStream
        
        # Set Icon
        Invoke-WebRequest -Uri $rcedit_download_url -OutFile rcedit.exe
        if ($env:ICON -and (Test-Path $env:ICON) -and ($env:ICON -match '\.ico$')) {
          Write-Host "Setting icon: $env:ICON"
          .\rcedit.exe $env:OUTPUT --set-icon $env:ICON
        } else {
          Write-Host "Icon does not exist, skipping."
        }

        Remove-Item $archive, 7zS2con.sfx -Force
